require: rubocop-rails

AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "config/initializers/**/*"
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: '3.2.2'

Metrics/BlockLength:
  Max: 25
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Max: 120
Metrics/ClassLength:
  Max: 120
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Enabled:  false
Metrics/CyclomaticComplexity:
  Enabled:  false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/LineLength:
  Max: 120
